services:
  # 侧重于工具属性：网易云音乐下载器/工具箱
  lmmarisej-netease-music-toolbox:
    container_name: netease-music-toolbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - /vol3/1000/音乐/网易云/downloads:/app/downloads
      - ./config:/app/config
      - ./logs:/app/logs
      - ./backend:/app/backend
      - panns_data:/root/panns_data
    environment:
      - PORT=5000
    restart: unless-stopped

volumes:
  panns_data: